/*
CREATE TABLE Escuelas_Deportivas (
    id_escuela NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_escuela VARCHAR2(100) NOT NULL,
    tipo_escuela VARCHAR2(50) NOT NULL,
    telefono_contacto VARCHAR2(20),
    direccion VARCHAR2(255),
    ciudad VARCHAR2(100),
    region VARCHAR2(100)
);

CREATE TABLE Personal (
    id_personal NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR2(100) NOT NULL,
    profesion VARCHAR2(50) NOT NULL,
    nacionalidad VARCHAR2(50),
    fecha_nacimiento DATE,
    id_escuela NUMBER,
    CONSTRAINT fk_escuela_personal FOREIGN KEY (id_escuela) REFERENCES Escuelas_Deportivas(id_escuela)
);

CREATE TABLE Costos (
    id_costo NUMBER PRIMARY KEY,
    descripcion_costo VARCHAR2(255) NOT NULL,
    monto NUMBER NOT NULL,
    fecha DATE DEFAULT SYSDATE,
    id_escuela NUMBER,
    CONSTRAINT fk_escuela_costos FOREIGN KEY (id_escuela) REFERENCES Escuelas_Deportivas(id_escuela)
);

CREATE TABLE Instalaciones (
    id_instalacion NUMBER PRIMARY KEY,
    nombre_instalacion VARCHAR2(100) NOT NULL,
    direccion_instalacion VARCHAR2(255),
    capacidad NUMBER,
    id_escuela NUMBER,
    CONSTRAINT fk_escuela_instalacion FOREIGN KEY (id_escuela) REFERENCES Escuelas_Deportivas(id_escuela)
);
*/

/*
--Escuelas_Deportivas
INSERT INTO Escuelas_Deportivas (nombre_escuela, tipo_escuela, telefono_contacto, direccion, ciudad, region)
VALUES ('Escuela Fútbol Juvenil', 'Fútbol', '123456789', 'Av. Siempre Viva 742', 'Santiago', 'Metropolitana');

INSERT INTO Escuelas_Deportivas (nombre_escuela, tipo_escuela, telefono_contacto, direccion, ciudad, region)
VALUES ('Escuela de Básquet', 'Baloncesto', '987654321', 'Calle 123', 'Valparaíso', 'Valparaíso');

INSERT INTO Escuelas_Deportivas (nombre_escuela, tipo_escuela, telefono_contacto, direccion, ciudad, region)
VALUES ('Escuela de Natación', 'Natación', '456789123', 'Piscina Municipal', 'Concepción', 'Biobío');

INSERT INTO Escuelas_Deportivas (nombre_escuela, tipo_escuela, telefono_contacto, direccion, ciudad, region)
VALUES ('Escuela de Tenis', 'Tenis', '321654987', 'Calle Deportes 456', 'Antofagasta', 'Antofagasta');

--Personal
INSERT INTO Personal (nombre_completo, profesion, nacionalidad, fecha_nacimiento, id_escuela)
VALUES ('Juan Pérez', 'Entrenador', 'Chilena', TO_DATE('1985-06-15', 'YYYY-MM-DD'), 1);

INSERT INTO Personal (nombre_completo, profesion, nacionalidad, fecha_nacimiento, id_escuela)
VALUES ('Ana Gómez', 'Fisioterapeuta', 'Chilena', TO_DATE('1990-11-22', 'YYYY-MM-DD'), 2);

INSERT INTO Personal (nombre_completo, profesion, nacionalidad, fecha_nacimiento, id_escuela)
VALUES ('Carlos Sánchez', 'Entrenador', 'Argentina', TO_DATE('1980-03-10', 'YYYY-MM-DD'), 3);

INSERT INTO Personal (nombre_completo, profesion, nacionalidad, fecha_nacimiento, id_escuela)
VALUES ('Laura Fernández', 'Nutricionista', 'Uruguaya', TO_DATE('1992-08-05', 'YYYY-MM-DD'), 4);

--Costos
INSERT INTO Costos (id_costo, descripcion_costo, monto, id_escuela)
VALUES (1, 'Pago de entrenadores', 500000, 1);

INSERT INTO Costos (id_costo, descripcion_costo, monto, id_escuela)
VALUES (2, 'Compra de balones', 200000, 2);

INSERT INTO Costos (id_costo, descripcion_costo, monto, id_escuela)
VALUES (3, 'Mantenimiento de piscina', 300000, 3);

INSERT INTO Costos (id_costo, descripcion_costo, monto, id_escuela)
VALUES (4, 'Compra de raquetas', 150000, 4);

--Instalaciones
INSERT INTO Instalaciones (id_instalacion, nombre_instalacion, direccion_instalacion, capacidad, id_escuela)
VALUES (1, 'Cancha de Fútbol', 'Av. Siempre Viva 742', 500, 1);

INSERT INTO Instalaciones (id_instalacion, nombre_instalacion, direccion_instalacion, capacidad, id_escuela)
VALUES (2, 'Gimnasio Deportivo', 'Calle 123', 300, 2);

INSERT INTO Instalaciones (id_instalacion, nombre_instalacion, direccion_instalacion, capacidad, id_escuela)
VALUES (3, 'Piscina Olímpica', 'Piscina Municipal', 200, 3);

INSERT INTO Instalaciones (id_instalacion, nombre_instalacion, direccion_instalacion, capacidad, id_escuela)
VALUES (4, 'Canchas de Tenis', 'Calle Deportes 456', 100, 4);
*/       

SELECT * FROM Escuelas_Deportivas;
SELECT * FROM Personal WHERE id_escuela = 1;
SELECT * FROM Costos;
SELECT * FROM Instalaciones WHERE capacidad > 200;






